runtime: java8
service: 'backend'
inbound_services:
- warmup
derived_file_type:
- java_precompiled
auto_id_policy: default
api_version: 'user_defined'
handlers:
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: /api/v1/search-match
  script: unused
  login: optional
  secure: optional
- url: /api/v1/add-participant
  script: unused
  login: optional
  secure: optional
