name: JavaScript Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: yarn add eslint@latest
      - name: Install eslint React Plugin
        run: yarn add eslint-plugin-react@latest
      - name: Install Google style plugin
        run: yarn add eslint-config-google@latest
      - name: Lint with ESLint
        run: ./node_modules/.bin/eslint frontend/**/*.js
